---
name: Thomas
surname: Fung
position: Associate Professor in Statistics
address: School of Mathematical and Physical Sciences, Macquarie University
phone: +61 2 9850 4769
www: researchers.mq.edu.au/en/persons/thomas-fung
email: thomas.fung@mq.edu.au
linkedin: thomas-fung-dr
github: thomas-fung
headcolor: 414141
date: "`r format(Sys.time(), '%B %Y')`"
output: vitae::hyndman
params:
  full_cv: TRUE
  presentation_cutoff: 2019
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, warning = FALSE, message = FALSE)
library(tidyverse)
library(RefManageR)
library(glue)
library(vitae)
# source("functions.R") 
# if you want to ref R packages automatically
```

# Employment

```{r, employment, results = 'asis'}
tribble(
  ~Start, ~End, ~Position, ~ uni, 
  "01/2025", NA, "Associate Professor in Statistics", "School of Mathematical and Physical Sciences, Macquarie University",
  "01/2022", "12/2024", "Senior Lecturer in Statistics", "School of Mathematical and Physical Sciences, Macquarie University",
  "08/2018", "12/2021", "Senior Lecturer in Statistics", "Department of Mathematics and Statistics, Macquarie University",
  "01/2018", "08/2018", "Senior Lecturer in Statistics", "Department of Statistics, Macquarie University",
  "02/2010", "12/2017", 
  "Lecturer in Statistics", "Department of Statistics, 
  Macquarie University",
  "01/2010", "02/2010", "Research Assistant (Supervisor: Professor Neville Weber)", "School of Mathematics and Statistics, the University of Sydney",
  "07/2005", "02/2010", "Tutor", "School of Mathematics and Statistics, the University of Sydney") %>% 
  mutate(End = replace_na(End, "present")) %>%
  mutate(Years = paste(Start, "--", End, sep = "")) %>%
  select(Years, Position, uni) %>%
  detailed_entries(Position, Years, where = uni)
```


# Professional Service

```{r, service, results = 'asis'}
tribble(
  ~Start, ~End, ~Position, ~ uni, 
  "07/2024", NA, "Director of Education", NA,
  "10/2023", NA, "Summer School Officer", "The International Association for Statistical Computing (IASC)", 
  "11/2022", NA, "Deputy Course Director for BSc", "Faculty of Science & Engineering, Macquarie University", 
  "03/2022", "03/2023", "Vice-President", "SSA", 
  "01/2022", "12/2023", "Teaching Lead in Statistics", NA, 
  "03/2020", "03/2022", "President", "SSA", 
  "12/2019", "12/2023", "Board of Directors Ordinary Members", "The Asian Regional Section of The International Association for Statistical Computing (IASC-ARS)",
  "05/2019", "12/2021", "Teaching Lead in Statistics", "MQ2",
  "03/2019", "03/2020", "Vice-President", "SSA",
  "03/2019", NA, "Associate Editor", "Australian and New Zealand Journal of Statistics",
  "01/2019", "10/2019", "Statistics Seminar Organiser", "MQ1", 
  "02/2018", "06/2018", "Higher Degree Research (HDR) Director", "MQ1",
  "03/2016", "03/2018", "Secretary", "SSA",
  "10/2015", "06/2018", "Master of Research (MRes) Advisor", "MQ1",
  "03/2015", "03/2016", "Assistant Secretary", "SSA",
  "02/2014", "08/2014", "Statistics Seminar Organiser", "MQ1",
  "07/2013", "08/2014", "Undergraduate Studies Coordinator", "MQ1",
  "08/2010", "10/2010", "Postgraduate and Honour Coordinator", "MQ1"
  ) %>% 
  mutate(End = replace_na(End, "present"),
         uni = 
           replace_na(uni, "School of Mathematical and Physical Sciences, Macquarie University"),
         uni = case_when(
           uni == "SSA" ~ 
             "Statistical Society of Australia, NSW Branch",
           uni == "MQ1" ~ 
             "Department of Statistics, Macquarie University",
           uni == "MQ2" ~ 
             "Department of Mathematics and Statistics, Macquarie University",
           TRUE ~ uni
         )
           ) %>%
  mutate(Years = paste(Start, "--", End, sep = "")) %>%
  select(Years, Position, uni) %>%
  detailed_entries(Position, Years, where = uni)
```

```{asis, echo = params$full_cv}
# Research Interest
- My research interests include
    - (Integer-valued) Time Series Analysis
    - Flexible Regression
    - Conway-Maxwell Poisson (CMP) and related distributions
    - Variance-Gamma and related distributions
    - Tail dependence
- My research is motivated by complex data that exhibit deviations from an assumed model, such as dispersion, zero-inflation, skewness and heavy-tailedness.
```

# Publications

```{r publications_info}
pub <- scholar::get_publications("eworc5YAAAAJ") %>% 
  filter(!is.na(year), journal != "arXiv preprint arXiv:",
         journal != "World Statistics Congress of the International Statistical Institute", !stringr::str_detect(title, "Package")) %>% 
  mutate(author = stringr::str_replace(author, "AA BOMBACI BILGIN", "A Bilgin"), 
    journal = str_replace(journal, "&", "and"), 
    journal = glue::glue("{author}. {journal}, {number}")) %>% 
  arrange(desc(year), author)
```


## `r ifelse(!params$full_cv, paste("Selected"), paste(""))` Journal Publications

I have `r NROW(pub)` publications in international journals. `r ifelse(!params$full_cv, paste("Selected journal publications are listed below. "), paste(""))`

```{r publications_output_short, results = "asis", include=!params$full_cv}
pub %>% 
  slice_head(n = 5) %>% 
  detailed_entries(
    what = title,
    when = year,
    where = journal)
```

```{r publications_output_full, results = "asis", include = params$full_cv}
pub %>% 
  detailed_entries(
    what = title,
    when = year,
    where = journal,
    with = glue::glue("No. of citation: {cites}")
    ) 
```

## Software Development
```{r rpkgs}
tribble(
  ~ pkg, ~ when, ~role, ~details, ~author,
  "mq-letter-quarto", 2024, "Author", "Quarto template for Macquarie University Style letter", "T Fung", 
  "moostr", 2023, "Author", "Enhancing Exam Creation in Moodle with Customisable Rewards, Shuffling, and Tolerance Levels", "I Jiang, T Fung",
  "mq-thesis-quarto", 2023, "Author", "Macquarie University Thesis Quarto Template", "T Fung", 
  "mq-research-report-quarto", 2023, "Author", "Quarto template for Macquarie University consulting report", "T Fung",
  "mq-SoMAPS-research-report-latex", 2023, "Author", "LaTeX class file for a research report with the SoMAPS @ Macquarie University Branding", "T Fung", 
  "quarto-mq-revealjs-theme", 2022, "Author", "Macquarie University Quarto reveal.js Presentation Template", "T Fung, S Connor", 
  "mpcmp", 2020, "Author", "Mean-parametrized Conway-Maxwell Poisson Regression", "T Fung, A. Alwan, J. Wishart, A. Huang",
  "survivalMPLdc", 2020, "Author", "Penalised Likelihood for Survival Analysis with Dependent Censoring", 
  "J. Xu, J. Ma, T. Fung", 
  "qicpack", 2019, "Author", "QIC package for GEE",
  "T. Fung",
  "thesisdownmq", 2018, "Author", 
  "An updated R Markdown thesis template using the bookdown package for Macquarie University HDR Thesis",
  "T. Fung, J. Wishart") %>% 
  arrange(-when, author) %>% 
  detailed_entries(glue("\\textbf{<pkg>}: <details>", .open = "<", .close = ">"), when, where = author, .protect = FALSE)
```

# Honours and Awards
```{r honours}
tribble(
  ~ award, ~ when,  
  "FSE Excellent Awards for Teaching Innovation", 2024,
  "Vice-Chancellor's Excellence Awards for Excellence in Education. Learning and Teaching Innovation Award. Highly Commended (Team)", 2024,
  "FSE Excellent Award for Educational Leader", 2023,
  "FSE Excellence Award for Inter-School Collaboration", 2023,
  "60 Australian statisticians, showcasing the breadth of the Australian statistical community to celebrate the 60th anniversary of the Statistical Society of Australia", 2023,
  "Statistical Society of Australia President’s Award for Leadership in Statistics", 2022) %>% 
  arrange(-when) %>% 
  detailed_entries(award, when)
```


```{asis, echo=params$full_cv}
#  Teaching experience

I have extensive convening and teaching experience ranging from first year to master level, theoretical to applied units. 
```

```{r tutoring, include= params$full_cv}
tribble(
  ~ role, ~ unit,
  "Unit Convenor", "Coding and Communication in Statistics (STAT1378)",
  "Unit Convenor", "Statistical Data Analysis (STAT1371, formerly as STAT171)", 
  "Lecturer", "Introductory Statistics (STAT1170, formerly as STAT170)",
  "Unit Convener", "Modern Computational Statistical Methods (STAT8178,  formerly as STAT878)",
  "Unit Convenor", "Applied Statistics (STAT2170/6180, formerly as STAT270/680)",
  "Lecturer", "Statistical Inference (STAT306/806)", 
  "Unit Convenor", "Generalized Linear Models (STAT8111, formerly as STAT811)",
  "Unit Convenor", "Research Frontiers in Statistics (STAT7900, formerly as STAT700)", 
  "Unit Convenor", "Stochastic Finance (STAT890, rested)", 
  "Unit Convenor", "Computer Simulation (STAT2178, formerly as STAT278)",
  "Lecturer", "Research Data Analysis (MEDI7002)",
  "Lecturer", "Statistical Theory (STAT810)", 
  "Unit Convenor", "Statistical Design (STAT6114, formerly as STAT814)",
  "Unit Convenor", "Statistical Modelling in Finance and Insurance (ACST602)", 
  "Lecturer", "Prelude to Bioinformatics (STAT8830, formerly as STAT830)", 
  "Lecturer", "Computer Applications in Business (MIST800)",
  "Lecturer", "Gambling, Sport and Medicine (STAT175)",
  "Unit Convenor", "Graphics, Multivariate Methods and Data Mining (STAT3102, formerly as STAT302)"
  ) %>% 
  arrange(desc(role)) %>% 
  detailed_entries(unit, role)
```

```{asis, echo=params$full_cv}
# Named Lectures
```

```{r presentation_named, include= params$full_cv}
tribble(
  ~year, ~ named, ~ location,
  2020, "H.O. Lancaster Lecture", "Statistical Society Australia"
) %>% 
  detailed_entries(named, year, where = location)
```

```{r presentation, include= params$full_cv, results = "asis"}
glue::glue("# Other presentations since  {params$presentation_cutoff}")
tribble(
  ~ years, ~ days, ~ conf, ~ location,
  2024, "August 27-30", "COMPSTAT 2024", "Giessen, Germany",
  2024, "June 25-26", "EAC-ISBA Conference 2024", "Online", 
  2024, "June 20", "BDSI Interactive Forum Series", "Biological Data Science Institute, ANU", 
  2024, "June 20", "Statistic seminar", "Research School of Finance, 
Actuarial Studies and Statistics, ANU",
  2023, "December 11-14", "ASC 2023", "Wollongong, Australia",
  2023, "August 1-3", "EcoSta", "Tokyo, Japan", 
  2023, "July 15-20", "64th World Statistical Congress", 
 "Ottawa, Canda",
 2022, "December 12-13", "IASC-ARS Interim Conference 2022", "Online Conference",
 2022, "Februry 21-24", "IASC-ARS 2022", "Online Conference",
  2021, "July 5--9", "ANZSC 2021", "Online Conference",
  2019, "August 18--23", "62nd World Statistical Congress",
 "Kuala Lumpur, Malaysia",
 2019, "June 25--27", "EcoSta", "Taichung, Taiwan",
 2018, "October 31", "Statistics Seminar", 
 "Department of Statistics and Actuarial Science, University of Hong Kong, Hong Kong",
 2018, "October 28", "Statistics Seminar", "International Centre for Mathematical Research, Peking University, China",
 2018, "October 11", "Statistics Seminar", "Department of Statistics and Actuarial Science, University of Hong Kong, Hong Kong",
 2018, "September 13", "Statistics Seminar", "Research School of Finance, Actuarial Studies and Statistics (RSFAS), Australian National University, Australia",
 2018, "August 26--30", "ISCB/ASC 2018", "Melbourne, Australia",
 2018, "August 26-30", "Statistics Seminar", "Duke-NUS, Singapore",
 2018, "July 28--August 2", "Joint Statistical Meetings (JSM)", 
 "Vancouver, Canada",
 2017, "December 16--18", "CMStatistics", "London, UK", 
 2017, "September 20", "NIASRA Seminar Series", "University of Wollongong, Australia", 
 2017, "July 16--21", "61st World Statistics Congress", 
 "Marrakech, Morocco", 
 2017, "June 15--17", "EcoSta", "Hong Kong, China",
 2016, "December 5--9", "Australian Statistical Conference (ASC)", 
 "Canberra, Australia", 
 2016, "July 30--August 4", "JSM", "Chicago, USA",
 2015, "July 26--31", "60th World Statistics Congress",
 "Rio de Janeiro, Brazil",
 2015, "March 28", "Statistics Seminar", "School of Mathematics and Statistics, USYD, Australia",
 2014, "September 25", "Statistics Seminar", "Department of Mathematics, University of Maryland, USA",
 2014, "September 22", "RIT on Financial Mathematics", "Department of Finance, University of Maryland, USA",
 2014, "September 9", "The Robust Statistics and Extremes Conference",
 "Canberra, Australia",
 2014, "September 4", "Statistics Seminar", "Department of Statistics, University of Auckland, New Zealand",
 2014, "July 7--10", "ASC/IMS Conference", "Sydney, Australia",
 2014, "May 23", "Statistics Seminar", ", UNSW, Australia",
 2013, "September 30", "57th Annual Meeting of the Australian Mathematical Society", "Sydney, Australia",
 2013, "August 25--30", "59th World Statistics Congress", "Hong Kong, China",
 2012, "July 9--12", "ASC", "Adelaide, Australia",
 2011, "December 28--30", "Statistical Concepts and Methods for the Modern World", "Colombo, Sri Lanka",
 2011, "August 21--26", "58th World Statistics Congress", 
 "Dublin, Ireland",
 2010, "December 6--10", "ASC", "Fremantle, Australia",
 2010, "March 5", "Statistics Seminar", "School of Mathematics and Statistics, USYD, Australia",
 2008, "June 30--July 3", "ASC", "Melbourne, Australia",
 2008, "May 16", "Statistics Seminar", "School of Mathematics and Statistics, the University of Sydney, Australia",
 2007, "April 13--14", "Young Statisticians Conference", "Canberra, Australia"
) %>% filter(years >= params$presentation_cutoff) %>% 
  detailed_entries(what = conf, when = glue::glue("<years>, <days>", .open = "<", .close = ">"), where = location, .protect = FALSE)
```

```{r conf_organisation, include= params$full_cv, results = "asis"}
glue("# Conference organisation")
tribble(
  ~ years, ~ days, ~ conf, ~location, ~ details, ~committee, 
  2023, "December", "Australian Statistical Conference", "Wollogong, Australia", "Secretary of the Local Organising Committee", TRUE, 
  2023, "December", "IASC-ARS Conference at Macquarie University", "Sydney, Australia",  "Chair of the Organising Committee", TRUE, 
  2022, "Februry", "IASC-ARS 2022", "Kyoto, Japan", "Scientific Program Committee", TRUE, 
  2019, "December", "IASC-ARS 2019", "Hong Kong", "Recent Advances in Modelling Complex Data", FALSE, 
  2018, "June", "EcoSta", "Hong Kong", "Recent advance in (semi)parametric modelling", FALSE, 
  2017, "December", "AustMS", "Sydney", "Stochastic models and applications", FALSE
) %>% 
   detailed_entries(what = glue::glue("<conf>, <location>", 
                                .open = "<", .close = ">"
                                ), 
                    when = 
                      glue::glue("<years>, <days>", .open = "<", .close = ">"),
                    where = ifelse(!committee, paste0("Organiser of the invited paper session: ", details), details), .protect = FALSE)
```

```{r int_research_fund, results = 'asis', include= params$full_cv}
glue("# Internal Research Funding")
tribble(
  ~ start, ~end, ~amount,  ~scheme, ~details, 
  "04/2024", "04/2027", "450393", "Cochlear Macquarie University Joint Fund", "Rapid, cheap, and informative hearing screening for all, with B. Liquet, G. Sofronov, S. Boothalingam & Z. Smith", 
  "07/2018", "12/2018", "6850", "Macquarie University OSP Travel Grant", "", 
  "08/2014", "01/2015", "6850", "Macquarie University OSP Travel Grant", "",
  "01/2012", "12/2012", "19194", "Macquarie University New Staff Research Grants Scheme", ""
) %>% mutate(end = replace_na(end, "present")) %>%
  mutate(years = paste(start, "--", end, sep = ""),
         amount = 
           paste0("$", prettyNum(amount, 
                                  big.mark = ",",
                                  scientific = FALSE)),
         scheme = paste0(scheme, ". ", amount)) %>%
  select(years, scheme, details) %>%
  detailed_entries(scheme, years, where = details)
```

```{asis, echo=params$full_cv}
# Internal Learning and Teaching Funding
```

```{r, results = "asis", include = params$full_cv}
tribble(
  ~ start, ~end, ~amount, ~scheme, ~ details,
  "02/2024", NA, "4402", "FSE Teaching Development Grant", "Empowering First-Year Students: A Three-Pillar Approach to Fostering Statistical Literacy, with J. Lin",
  "02/2024", NA, "2000", "FSE Teaching Development Grant", 
  "You to the Power of Visualization – a data visualisation challenge to enhance sustainability, employability, and student experience, with I. Jiang",
  "09/2022", "12/2022", "5000", "FSE Teaching Development Grant", "DataFest@Macquarie, with I. Jiang",
  "01/2017", "12/2017", "30451", "Macquarie University's Strategic Infrastructure Scheme (MQSIS) for Learning and Teaching",
  "Cloud-based virtual laboratory for large 
statistics units, with J. Wishart"
) %>% mutate(end = replace_na(end, "present")) %>%
  mutate(years = paste(start, "--", end, sep = ""),
         amount = 
           paste0("$", prettyNum(amount, 
                                  big.mark = ",",
                                  scientific = FALSE)),
         scheme = paste0(scheme, ". ", amount)) %>%
  select(years, scheme, details) %>%
  detailed_entries(scheme, years, where = details)
```

# External Consulting
```{r consulting, results='asis'}
tribble(~when, ~what, ~ where, 
        "12/2020", "Analysing Alcohol related Crime Statistics at Buronga & Gol Gol, NSW", "Adams Hospitality") %>% 
   detailed_entries(where, when, where = what)
```

```{asis, echo=!params$full_cv}
# Technical Skills
General skills in statistics, mathematics and computing. 

- Languages: Cantonese (native), English (fluent), Mandarin (intermediate)
- Mathematical/statistical software: R, Matlab, Minitab,  SPSS, IBM SPSS Modeler and Mathematica,
- Computing: Mac, WINDOWS, Linux, Microsoft Office (Word, Excel, Powerpoint, Access/SQL), \LaTeX.
```

```{asis, echo= params$full_cv}
# Selected academic visits
```

```{r visits, results = 'asis', include = params$full_cv}
tribble(
  ~ when, ~ what, ~ where,
  "11/2018", "NSW Bureau of Crime Statistics and Research, Department of Justice, Sydney, Australia", "4 weeks",
 "09/2018", "Department of Statistics & Actuarial Science, University of Hong Kong, Hong Kong, China", "9 weeks",
 "08/2018", "School of Physical & Mathematical Sciences, (NTU), Singapore", "3 weeks",
 "07/2018", "Quality Systems and Reporting, Climate and Atmospheric Science Branch, Office of Environment and Heritage (NSW), Sydney, Australia", "4 weeks",
 "11/2014", "School of Mathematics and Statistics, the University of Sydney, Australia", "10 weeks",
 "09/2014", "Department of Finance, University of Maryland, USA", "9 weeks",
 "08/2014", "Department of Statistics, University of Auckland, New Zealand", "5 weeks"
) %>% 
  detailed_entries(what, when, where)
```


```{asis, echo=params$full_cv} 
# Research Supervision
## Postdoctoral researcher
```

```{r post_doc, results = "asis", include = params$full_cv}
tribble(
  ~ start, ~ end, ~ name,
  "01/2020", "12/2020", "Manjula Schou", 
  "04/2012", "9/2012", "Joanna Wang"
) %>% mutate(end = replace_na(end, "present")) %>%
  mutate(years = paste(start, "--", end, sep = "")) %>%
  select(years, name) %>%
  brief_entries(name, years)
```


```{asis, echo = params$full_cv}
## Ph.D Thesis
```

```{r supervision_data}
supervision_data <- tribble(
  ~start, ~end, ~role, ~ name, ~details, ~ type, 
  "01/2022", "02/2023", "Co-supervision", "Christina Feng", 
  "Climate and Assault Hospitalisation", "mres",
  "02/2021", "03/2022", "Co-supervision", "Vanessa Neo", 
  "Inconsistent coral bleaching risk indicators between temperature data sources", "mres",
  "02/2014", "02/2017", "Co-supervision", "Jamil hasan Karami", 
  "An Extension of Model Selection Curves Framework to Accelerated Failure Time Models", "phd",
  "06/2019", "06/2019", "", "Yaxin Yu", "Analysis of influences of 2014 Liquor Reforms Act on domestic violence in Sydney (NSW 2000) and NSW, Australia", "master",
  "06/2019", "06/2019", "", "Jess Chen", "The comparisons of data mining methods for the predictive accuracy of probability of default for LeadingClub's loan data", "master",
 "06/2019", "06/2019", "", "Katelyn Priester", "Predictors of Acute Pain after Thoracic Surgery", "master",
 "06/2017", "06/2017", "", "Sze Ho Wang", "Prediction of daily maximum ozone concentrations from ozone precursors and meteorological conditions using Multiple Linear Regression and Generalized Linear Model", "master", 
"06/2016", "06/2016", "", "Ahmad Alqabandi", 
"Analysing the Impact of Lockout Law on Alcohol-Related Assaults in NSW Using GLARMA Model", "master",
"06/2016", "06/2016", "", "Haolun Deng", "Estimation of Skew Models in WinBUGS and Stan", "master",
"06/2014", "06/2014", "", "Jian Zheng Xie", "Modelling and Predicting Stocks Price with ARMA-GARCH Model", "master",
"06/2014", "06/2014", "", "Brook Naar", "Fixed Form Variational Bayes Posterior Estimation through Regression -- Review and Discussion", "master", 
"11/2013", "11/2013", "", "Ling Chen", "A Study on Pricing Motor Compulsory Third party Liability Insurance in China using GLM techniques.", "master",
"11/2013", "11/2013", "", "Gavin Marsh", "Skew Brownian Motion and Pricing European Options", "master",
"11/2012", "11/2012", "", "Zhongkai Chan",
  "Modelling high frequency financial time series by the decomposition model", "master"
)
```

```{r phd, results="asis", include = params$full_cv}
supervision_data %>% filter(type == "phd") %>% 
  mutate(end = replace_na(end, "present")) %>%
  mutate(years = paste(start, "--", end, sep = ""),
         name = paste0(role, " of ", name)) %>%
  select(years, name, details) %>%
  detailed_entries(name, years, where = details)
```

```{asis, echo=params$full_cv}
## MRes Project
```
```{r mres, results="asis", include = params$full_cv}
supervision_data %>% filter(type == "mres") %>% 
  mutate(end = replace_na(end, "present")) %>%
  mutate(years = paste(start, "--", end, sep = ""),
         name = paste0(role, " of ", name)) %>%
  select(years, name, details) %>%
  detailed_entries(name, years, where = details)
```


```{asis, echo=params$full_cv}
## Master Coursework Research Project
```

```{r master, results="asis", include = params$full_cv}
supervision_data %>% filter(type == "master") %>% 
  mutate(end = replace_na(end, "present")) %>%
  mutate(years = end) %>%
  select(years, name, details) %>%
  detailed_entries(name, years, where = details)
```

# Education

```{r degrees, results='asis'}
tribble(
  ~ degree, ~ loc, ~ dates, ~ details,
  "Ph.D. in Statistics", "School of Mathematics and Statistics, the University of Sydney", "2010", "Supervisor: Emeritus Professor Eugene Seneta",
  "B.Sc.(Advanced Mathematics) Honours Class I","School of Mathematics and Statistics, the University of Sydney", "2006", "Supervisor: Emeritus Professor Eugene Seneta") %>% 
  detailed_entries(degree, dates, where = loc, why = details)
```

```{asis, echo = params$full_cv, include = params$full_cv}
# Refereeing

Annals of the Institute of Statistical Mathematics, Australian and New Zealand Journal of Statistics, Biometric, Communication in Statistics - Theory and Methods,  Computational Statistics, Econometrics and Statistics, Empirical Economics, Entropy, International Journal of Theoretical and Applied Finance, International Statistical Review, Journal of Applied Mathematics, Journal of Computational and Graphical Statistics, Journal of Multivariate Analysis, Journal of Statistical Computation and Simulation, Journal of Statistical Theory and Practice, Mathematics, PLOS ONE, Songklanakarin Journal of Science and Technology, Statistics and Probability Letters.
```



